"""empty message

Revision ID: 00b737c780e3
Revises: 
Create Date: 2021-09-03 23:46:42.370678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b737c780e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('person',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('homeworld_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeworld_uid'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('vehicle_class', sa.String(length=50), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('pilot_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['pilot_uid'], ['person.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorito_person', sa.Integer(), nullable=True),
    sa.Column('favorito_planet', sa.Integer(), nullable=True),
    sa.Column('favorito_vehicle', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorito_person'], ['person.uid'], ),
    sa.ForeignKeyConstraint(['favorito_planet'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['favorito_vehicle'], ['vehicle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_favorites')
    op.drop_table('vehicle')
    op.drop_table('person')
    op.drop_table('user')
    op.drop_table('planet')
    # ### end Alembic commands ###
